### PR TITLE
Default option param to empty hash in content_entries index

### PR DESCRIPTION
**Pull request by dfranciosi**
Avoid NoMethodError: undefined method `[]' for nil:NilClass if no
options

### CODE REVIEW

**Comment by did** [comment]
@dfranciosi, what's the problem with old code?  when options is nil, it's not a problem since we've got that `options || {}`. Perhaps, you could write a small spec to describe the issue.
Anyway, thanks for your help!

**Comment by dfranciosi** [comment]
@did It happens at line 23 for `options[:page] || 1`.
No problem to add a test for it, I'm going also to reintroduce `bundler` dependency used in CI

**Comment by did** [comment]
@dfranciosi I didn't see that line. Good point! So just write a very simple test here (https://github.com/locomotivecms/coal/blob/master/spec/integration/resources/content_entries_spec.rb#L25). thanks again!

**Comment by dfranciosi** [comment]
@did ok to merge?

**Comment by did** [comment]
@dfranciosi that's awesome! 👍  thanks!

**Pull request merged**
